#618 Add TestPlan to IG Testing Artifacts
HL7/fhir-ig-publisher pull request #676
Opened 2023-04-24 22:48 UTC by rettema

### What does this Pull Request do?
Add logic that links TestPlan resources to Profiles (StructureDefinitions).

### Why?
The FHIR community has been increasingly interested in provided better support for testing artifacts within IGs. This logic is an additional enhancement that allows IGs generated from the HL7 IG template to incorporate and list TestPlan resources with their associated FHIR Profiles (StructureDefinitions).

* [#618](https://github.com/HL7/fhir-ig-publisher/issues/618)

2023-04-25 21:15 UTC, lmckenzi requested changes
Check for ref.getReference() being null, otherwise looks good.

2023-04-25 21:25 UTC, rettema commented
null check added; please review (again)

2023-04-25 21:48 UTC, lmckenzi approved these changes

2023-04-27 00:14 UTC, grahamegrieve approved these changes
ok

2023-04-27 00:14 UTC, merged